### ISSUE TITLE
ffmpeg is not found on Ubuntu 16.04

### ISSUE THREAD

**Issue by MehmetCagriK** [JoanMartin/trackanimation#1]
Hey, I am having the error below. Is there a quick fix for Ubuntu 16.04?
"""
Traceback (most recent call last):
  File "examples.py", line 30, in <module>
    fig.makeVideo(output_file='simple-example', framerate=60, linewidth=1.0)
  File "/home/cagri/penv/trackanimation/trackanimation/animation.py", line 164, in makeVideo
    pipe = subprocess.Popen(cmdstring, stdin=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
"""

**Comment by JoanMartin** [comment]
Hi @MehmetCagriK 
sorry for the delay in replying!

Do you have **ffmpeg** installed?
