### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by goosst** [JoanMartin/trackanimation#13]
Hello

The toolbox looks very interesting but I can't seem to get any of the examples to run with AnimationTrack(...)
it always stumbles upon a `HTTP Error 429: Too Many Requests`

```
fig = AnimationTrack(df_points=ibiza_trk, dpi=300, bg_map=True, map_transparency=0.5)
Lowered zoom level to keep map size reasonable. (z = 11)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stijn/Projects/gpxstuff/trackanimation/trackanimation/animation.py", line 68, in __init__
    self.map.append(smopy.Map((min_lat, min_lng, max_lat, max_lng)))
  File "/home/stijn/.local/lib/python3.8/site-packages/smopy.py", line 292, in __init__
    self.fetch()
  File "/home/stijn/.local/lib/python3.8/site-packages/smopy.py", line 324, in fetch
    self.img = fetch_map(self.box_tile, self.z)
  File "/home/stijn/.local/lib/python3.8/site-packages/smopy.py", line 65, in fetch_map
    img.paste(fetch_tile(x, y, z), (px, py))
  File "/home/stijn/.local/lib/python3.8/site-packages/smopy.py", line 45, in fetch_tile
    png = BytesIO(urlopen(url).read())
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
```
Any known issue?

**Comment by goosst** [comment]
ok, seems this fixes it `pip3 install --upgrade smopy`

**Comment by dulietina** [comment]
@goosst I encounter the same problem but upgrading smopy won't solve the issue. would it be possible for you to check the version of the main packages in use? may be that some version combo does the trick...
